[tool.poetry]
name = "blint"
version = "2.0.0"
description = "Linter for binary files powered by lief"
authors = ["Prabhu Subramanian <prabhu@appthreat.com>"]
maintainers= ["Prabhu Subramanian <prabhu@appthreat.com>", "Caroline Russell <caroline@appthreat.dev>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/OWASP-dep-scan/blint"
repository = "https://github.com/OWASP-dep-scan/blint"
keywords = ["linter", "binary", "security", "sast"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "Topic :: Utilities",
    "Topic :: Security",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
include = ["blint/data/*.yml"]

[tool.poetry.urls]
"CI" = "https://github.com/AppThreat/blint/actions"

[tool.poetry.scripts]
blint = 'blint.cli:main'

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
lief = "^0.12.3"
rich = "^13.4.1"
PyYAML = "^6.0"
defusedxml = "^0.7.1"
pydantic = {version = "^2.6.0", extras = ["email"]}

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
black = "^24.0.0"
flake8 = "^7.0.0"
pytest-cov = "^4.0.0"
pyinstaller = "^6.3.0"

[tool.black]
line-length = 80

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--verbose --cov-append --cov-report term --cov blint"

[tool.flake8]
ignore = "E203, E266, E501, W503, W605"
max-line-length = 80
max-complexity = 18
select = "B,C,E,F,W,T4,B9"
